<?php

/**
 * @file
 * This module enables AYAH game functionality:
 * administrators can add a game to desired forms that users without
 * the 'skip AYAH' permission (typically anonymous visitors) have to play.
 *
 */


/**
 * Implements hook_menu().
 */
function ayah_menu() {
  $items = array();

  $items['admin/config/people/ayah'] = array(
    'title' => 'AYAH',
    'description' => 'Administer how and where AYAH games are used.',
    'file' => 'ayah.admin.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ayah_admin_settings'),
    'access arguments' => array('administer AYAH settings'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/user/ayah/ayah_game'] = array(
    'title' => 'AYAH game administration',
    'file' => 'ayah.admin.inc',
    'page callback' => 'ayah_game_admin',
    'page arguments' => array(4, 5),
    'access arguments' => array('administer AYAH settings'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}


/**
 * Implements hook_perm().
 */
function ayah_perm() {
  return array(
    'administer AYAH settings' => array(
      'title' => t('Administer AYAH settings'),
    ),
    'skip AYAH' => array(
      'title' => t('Skip AYAH'),
      'description' => t('Users with this permission will not be offered a AYAH game.'),
    ),
  );
}


/**
 * Implements hook_theme().
 */
function ayah_theme() {
  return array(
    'ayah_admin_settings_ayah_listforms' => array(
      'render element' => 'form',
    ),
    'ayah' => array(
      'render element' => 'element',
    ),
  );
}


/**
 * Implements hook_element_info().
 */
function ayah_element_info() {
  // Define the AYAH form element with default properties.
  $ayah_element = array(
    '#input' => TRUE,
    '#process' => array('ayah_element_process'),
    '#default_value' => '',
    '#ayah_validate' => 'ayah_validate_game',
  );
  return array('ayah' => $ayah_element);
}


/**
 * Process callback for AYAH form element.
 */
function ayah_element_process($element, &$form_state, $complete_form) {
  // Prevent caching of the page with AYAH elements.
  // This needs to be done even if the AYAH will be ommitted later:
  // other untrusted users should not get a cached page when
  // the current untrusted user can skip the current AYAH.
  global $conf;
  $conf['cache'] = FALSE;

  $element['#element_validate'] = array('ayah_validate');
  $element['#theme'] = 'ayah';

  // Get the form ID of the form we are currently processing (which is not
  // necessary the same form that is submitted (if any).
  $this_form_id = $complete_form['form_id']['#value'];

  // Need to check for multi-part and previews.
  //
  // Store AYAH information for further processing in
  // - $form_state['ayah_info'], which survives a form rebuild such as
  //   a preview), useful in _captcha_get_posted_captcha_info().
  // - $element['#ayah_info'], for post processing functions that do not
  //   receive a $form_state argument such as a pre_render callback.
  $form_state['ayah_info'] = array(
    'this_form_id' => $this_form_id,
  );
  $element['#ayah_info'] = array(
    'form_id' => $this_form_id,
  );
  return $element;
}

/**
 * Theme function for a AYAH element.
 *
 */
function theme_ayah($variables) {
  $element = $variables['element'];
  $ayah_web_service_host = "ws.areyouahuman.com";
  $ayah_publisher_key = variable_get('ayah_publisher_key', '');
  $url = 'https://' . $ayah_web_service_host . "/ws/script/" . urlencode($ayah_publisher_key);
  return "<div id='AYAH'></div><script src='" . $url . "'></script>";
}

/**
 * Implements hook_form_alter().
 *
 * This function adds a AYAH game to forms for untrusted users if needed.
 */
function ayah_form_alter(&$form, $form_state, $form_id) {
  if (arg(0) != 'admin' || variable_get('ayah_allow_on_admin_pages', FALSE)) {
    module_load_include('inc', 'ayah');
    if (!user_access('skip AYAH')) {
      // See if we need to add the game for this form_id.
      $ayah_form = ayah_get_form_id_setting($form_id);
      if (isset($ayah_form->add_game) && $ayah_form->add_game){
        // Build AYAH form element.
        $ayah_element = array(
          '#type' => 'ayah',
        );
        // Get placement in form and insert in form.
        $ayah_placement = _ayah_get_ayah_placement($form_id, $form);
        _ayah_insert_game_element($form, $ayah_placement, $ayah_element);
      }
    }
  }
  // Add a warning about caching on the Perfomance settings page.
  if ($form_id == 'system_performance_settings') {
    $icon = theme('image', array('path' => 'misc/watchdog-warning.png', 'width' => 18, 'height' => 18, 'alt' => t('warning'), 'title' => t('warning')));
    $form['caching']['ayah'] = array(
      '#type' => 'item',
      '#title' => t('AYAH'),
      '#markup' => t('!icon The AYAH module will disable the caching of pages that contain a AYAH game.', array(
        '!icon' => '<span class="icon">' . $icon . '</span>')
      ),
      '#attributes' => array('class' => array('warning')),
    );
  }
}


/**
 * AYAH validation handler.
 *
 * This function is placed in the main ayah.module file to make sure that
 * it is available (even for cached forms, which don't fire
 * ayah_form_alter(), and subsequently don't include additional include
 * files).
 */
function ayah_validate($element, &$form_state) {

  $ayah_info = $form_state['ayah_info'];
  $form_id = $ayah_info['this_form_id'];

  module_load_include('inc', 'ayah');
  $session_secret = NULL;
  if (array_key_exists("session_secret", $_REQUEST)) {
    $session_secret = $_REQUEST["session_secret"];
  }
  $ayah_web_service_host = 'ws.areyouahuman.com';
  $is_a_human = FALSE;
  if ($session_secret) {
    $url = 'https://' . $ayah_web_service_host . "/ws/scoreGame";
    $fields = array(
      'session_secret' => urlencode($session_secret),
      'scoring_key' => variable_get('ayah_scoring_key', ''),
    );
    $resp = _ayah_doCall($url, $fields);
    if ($resp) {
      $is_a_human = ($resp->status_code == 1);
    }
  }
  if (!$is_a_human) {
    // Wrong answer, set form error.
    form_set_error('ayah_response', t("You didn't pass the game"));
    // If the AYAH game was on a login form: stop validating, quit the current
    // request and forward to the current page (like a reload) to prevent
    // loging in. We do this because the log in procedure, which happens after
    // ayah_validate(), does not check error conditions of extra form elements
    // like the the AYAH game.
    if ($form_id == 'user_login' || $form_id == 'user_login_block') {
      drupal_goto($_GET['q']);
    }
  }
}
